print("Hello Friend: ")
print("This is your 1st project : Band -Name-Generator")
city=input("Enter the city where you grow: ")
pet=input("Enter the name of a pet: ")
bandname=(city + pet)
print(bandname)